version: '3.8'
services:
  database:
    image: postgres:17.2-alpine3.21
    restart: on-failure
    environment: 
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - database:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
  cache:
    image: redis:7.4.2-alpine
    restart: on-failure
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    volumes: 
      - cache:/data
  rate-limiter-core:
    build:
      context: ./rate-limiter-core
    ports:
      - '3000:3000'
    depends_on:
      - database
      - cache
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    volumes:
      - ./rate-limiter-core:/rate-limiter-core
volumes:
  database:
    driver: local
  cache:
    driver: local