# check_if_request_is_allowed — token bucket
def test_check_if_request_is_allowed_token_bucket_allows_first_request_with_no_prior_redis_state(): pass
def test_check_if_request_is_allowed_token_bucket_allows_request_when_bucket_has_available_tokens(): pass
def test_check_if_request_is_allowed_token_bucket_denies_request_when_bucket_is_empty(): pass
def test_check_if_request_is_allowed_token_bucket_refills_tokens_proportional_to_elapsed_time(): pass

# check_if_request_is_allowed — leaking bucket
def test_check_if_request_is_allowed_leaking_bucket_allows_first_request_with_no_prior_redis_state(): pass
def test_check_if_request_is_allowed_leaking_bucket_allows_request_when_queue_length_is_below_window_size(): pass
def test_check_if_request_is_allowed_leaking_bucket_denies_request_when_queue_length_equals_window_size(): pass

# check_if_request_is_allowed — fixed window
def test_check_if_request_is_allowed_fixed_window_allows_first_request_with_no_prior_redis_state(): pass
def test_check_if_request_is_allowed_fixed_window_allows_request_when_count_is_below_rate_limit(): pass
def test_check_if_request_is_allowed_fixed_window_denies_request_when_request_count_equals_rate_limit(): pass
def test_check_if_request_is_allowed_fixed_window_resets_count_and_allows_request_after_window_elapses(): pass

# check_if_request_is_allowed — sliding window log
def test_check_if_request_is_allowed_sliding_window_log_allows_first_request_with_no_prior_redis_state(): pass
def test_check_if_request_is_allowed_sliding_window_log_allows_request_when_in_window_timestamp_count_is_below_limit(): pass
def test_check_if_request_is_allowed_sliding_window_log_denies_request_when_in_window_timestamp_count_equals_limit(): pass
def test_check_if_request_is_allowed_sliding_window_log_excludes_timestamps_older_than_window_duration_from_count(): pass

# check_if_request_is_allowed — sliding window counter
def test_check_if_request_is_allowed_sliding_window_counter_allows_first_request_with_no_prior_redis_state(): pass
def test_check_if_request_is_allowed_sliding_window_counter_allows_request_when_weighted_estimate_is_below_limit(): pass
def test_check_if_request_is_allowed_sliding_window_counter_denies_request_when_weighted_estimate_meets_or_exceeds_limit(): pass

# check_if_request_is_allowed — error and lock behaviour
def test_check_if_request_is_allowed_raises_for_invalid_user_credentials(): pass
def test_check_if_request_is_allowed_raises_for_service_that_does_not_exist(): pass
def test_check_if_request_is_allowed_raises_for_rule_that_does_not_exist(): pass
def test_check_if_request_is_allowed_persists_updated_algorithm_state_to_redis_after_decision(): pass
def test_check_if_request_is_allowed_releases_redis_lock_even_when_exception_is_raised(): pass

# increment_rate_limit_usage
def test_increment_rate_limit_usage_token_bucket_decrements_last_token_count_in_redis_by_one(): pass
def test_increment_rate_limit_usage_leaking_bucket_appends_request_details_to_queue_in_redis(): pass
def test_increment_rate_limit_usage_fixed_window_increments_fw_num_requests_in_redis(): pass
def test_increment_rate_limit_usage_sliding_window_log_appends_current_timestamp_to_redis_log(): pass
def test_increment_rate_limit_usage_sliding_window_counter_increments_current_window_count_and_purges_old_window_keys(): pass
def test_increment_rate_limit_usage_releases_redis_lock_even_when_exception_is_raised(): pass
def test_increment_rate_limit_usage_skips_state_update_when_redis_lock_cannot_be_acquired(): pass

# refresh_leaking_bucket_queue
def test_refresh_leaking_bucket_queue_populates_redis_list_with_one_entry_per_user_rule_combination(): pass
def test_refresh_leaking_bucket_queue_clears_existing_redis_list_entries_before_repopulating(): pass
def test_refresh_leaking_bucket_queue_results_in_empty_redis_list_when_no_leaking_bucket_rules_are_in_database(): pass

# manage_leaking_bucket_queues
def test_manage_leaking_bucket_queues_fires_queued_http_request_when_outflow_interval_has_elapsed(): pass
def test_manage_leaking_bucket_queues_does_not_fire_http_request_when_outflow_interval_has_not_yet_elapsed(): pass
def test_manage_leaking_bucket_queues_removes_processed_request_from_front_of_redis_queue(): pass
def test_manage_leaking_bucket_queues_returns_rule_key_to_leaking_bucket_rule_queue_after_processing(): pass
def test_manage_leaking_bucket_queues_releases_redis_lock_and_continues_when_exception_occurs(): pass
def test_manage_leaking_bucket_queues_exits_loop_when_shutdown_event_is_set(): pass
